ARRAY CREATION FUNCTIONS

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print("Array a:",a)

Array a: [1 2 3 4 5]


In [7]:
b=np.arange(0,15,2)
print("Array b:",b)

Array b: [ 0  2  4  6  8 10 12 14]


In [8]:
c=np.arange(0,15,3)
print('Array c:',c)

Array c: [ 0  3  6  9 12]


In [9]:
d=np.zeros((3,2))
print("Array D:",d)

Array D: [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
e=np.zeros((3,3),dtype=int)
print("Array E:",e)

Array E: [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [13]:
f=np.ones((2,4))
print("Array F:",f)

Array F: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
g=np.ones((4,2),dtype=int)
print("Array g:",g)

Array g: [[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [15]:
h=np.eye(3)
print("Identity Matrix:",h)

Identity Matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
h=np.eye(6)
print("identity matrix:\n",h)

identity matrix:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


ARRAY MANIPULATON FUNCTONS

In [18]:
a1=np.array([1,2,3])
reshape=np.reshape(a1,(1,3))
print("Reshaped array:",reshape)

Reshaped array: [[1 2 3]]


In [23]:
b1=np.array([1,2,3,4,5,6,7,8,9])
reshaped=np.reshape(b1,(9,1))
print("Reshaped array:",reshaped)

Reshaped array: [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [31]:
f1=np.array([[1,2,],[4,5],[7,8,]])
flattened=np.ravel(f1)
print("Flattened Array:\n",flattened)

Flattened Array:
 [1 2 4 5 7 8]


In [33]:
t1=np.array([[1,2,3],[4,5,6]])
transposed=np.transpose(t1)
print("Transposed Array:\n",transposed)

Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [34]:
a2=np.array([1,2,3])
b2=np.array([4,5,6])
stacked=np.vstack([a2,b2])
print("Stacked Array:\n",stacked)

Stacked Array:
 [[1 2 3]
 [4 5 6]]


MATHEMATICAL FUNCTION

In [35]:
add=np.array([1,2,3,4])
added=np.add(add,3)
print("Added 3 to g:\n",added)

Added 3 to g:
 [4 5 6 7]


In [37]:
squared = np.pow(add,4)
print("Squared 4 to g:\n",squared)

Squared 4 to g:
 [  1  16  81 256]


In [38]:
sqrt_val=np.sqrt(add)
print("Square rooted to add:\n",sqrt_val)

Square rooted to add:
 [1.         1.41421356 1.73205081 2.        ]


In [39]:
print(a)
print(b)

[1 2 3 4 5]
[ 0  2  4  6  8 10 12 14]


In [41]:
d2=np.array([1,2,3,4,5])
dot_product=np.dot(a,d2)
print("Dotted product:\n",dot_product)

Dotted product:
 55


STATISTICAL FUNCTIONS

In [42]:
s=np.mean([1,4,6,9])
mean=np.mean(s)
print("Mean:",mean)

Mean: 5.0


In [43]:
std_dev=np.std(s)
print("Standard deviation:",std_dev)

Standard deviation: 0.0


In [44]:
min=np.min(s)
print("Minimum value:",min)

Minimum value: 5.0


In [45]:
m=np.array([1,2,3,4,5])
mini=np.min(m)
print("minimum value:", mini)

minimum value: 1


In [46]:
maxi=np.max(m)
print("maximum value:",maxi)

maximum value: 5


LINEAR ALGEBRA FUNCTIONS

In [49]:
matrix=np.array([[1,2,3],[5,6,7]])
matrix

array([[1, 2, 3],
       [5, 6, 7]])

In [52]:
random_vals=np.random.rand(5)
print("Random Values:",random_vals)

Random Values: [0.86414043 0.49582075 0.30171517 0.40728674 0.30173246]


In [55]:
r = np.random.seed(0)
random_vals=np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


BOOLEAN & LOGICAL FUNCTIONS

In [59]:
logical_test=np.array([True,False,True])
all_true=np.all(logical_test)
print("All elements True:",all_true)

All elements True: False


In [60]:
logical_test=np.array([True,True,True])
all_true=np.all(logical_test)
print("All elements True:",all_true)

All elements True: True


SET OPERATION FUNCTION

In [69]:
set_a = np.array([1,2,3])
set_b = np.array([7,8,9,2,1])
intersection = np.intersect1d(set_a,set_b)
print("Intersection of a and b:",intersection)

Intersection of a and b: [1 2]


In [70]:
uni=np.union1d(set_a,set_b)
print("Union of a and b:",uni)

Union of a and b: [1 2 3 7 8 9]


ARRAY ATTRIBUTE FUNCTIONS

In [73]:
a=np.array([1,2,3,4])
shape=a.shape
print("shape of an array:",shape)

shape of an array: (4,)


In [74]:
a=np.array([1,2,3,4])
size=a.size
dim=a.ndim
nbyte=a.nbytes
item=a.itemsize
print("size of an array:",size)
print("dimensions of an array:",dim)
print("nbyte of an array:",nbyte)
print("itemsize of an array:",item)

size of an array: 4
dimensions of an array: 1
nbyte of an array: 32
itemsize of an array: 8


OTHER FUNCTIONS

In [75]:
a=np.array([1,2,3])
copied_array=np.copy(a)
print("copied array:",copied_array)

copied array: [1 2 3]


In [76]:
shared = np.shares_memory(a,copied_array)
print("Do two arrays share same memory?:",shared)

Do two arrays share same memory?: False


In [78]:
array_size_in_bytes=a.nbytes
print("size of a in bytes:",array_size_in_bytes)

size of a in bytes: 24
