Creating Arrays

In [1]:
my_list=[0,1,2,3,4,5,6]
my_list

[0, 1, 2, 3, 4, 5, 6]

In [2]:
type(my_list)

list

In [4]:
import numpy as np
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [5]:
type(arr)

numpy.ndarray

In [11]:
import numpy as np
np.arange(17)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [12]:
np.arange(2.0)

array([0., 1.])

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(25,15)

array([], dtype=int64)

In [17]:
np.arange(25,15,-1)

array([25, 24, 23, 22, 21, 20, 19, 18, 17, 16])

In [20]:
np.arange(-5,5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [21]:
np.arange(-20,-15)

array([-20, -19, -18, -17, -16])

In [22]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [23]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [24]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [2]:
import numpy as np
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [5]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [9]:
zero=np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [10]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
n=(2,3)
n1=(3,4)
print(np.zeros(n1))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
n=(2,3)
n1=(3,4)
print(np.zeros(n,dtype=int))

[[0 0 0]
 [0 0 0]]


In [17]:
np.ones(2)

array([1., 1.])

In [18]:
np.ones(2,dtype=int)

array([1, 1])

In [19]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [30]:
range(1,10)

range(1, 10)

In [32]:
list(range(2,10))

[2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
list(range(20,30))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

In [36]:
np.random.rand(6)

array([0.81573691, 0.14371007, 0.3852816 , 0.5565377 , 0.52091612,
       0.40557602])

In [37]:
np.random.rand(2,3)

array([[0.95915425, 0.99763578, 0.33466156],
       [0.55891643, 0.64031111, 0.56028734]])

In [38]:
np.random.rand(4,4)

array([[7.70551948e-01, 2.08443778e-01, 1.50876943e-01, 1.41266367e-01],
       [9.77106930e-01, 3.09381568e-01, 9.99820405e-01, 8.18719630e-01],
       [4.12890618e-01, 8.13538876e-01, 2.83435719e-01, 4.05402529e-01],
       [1.72335838e-02, 8.66177975e-01, 6.16880130e-04, 3.47765101e-01]])

In [41]:
np.random.randint(2,4)

2

In [42]:
np.random.rand(10,20,3)

array([[[0.84824571, 0.02924915, 0.290097  ],
        [0.47229453, 0.95140994, 0.09234884],
        [0.2711001 , 0.74064683, 0.71255774],
        [0.57449883, 0.68906309, 0.54338634],
        [0.20872531, 0.61958933, 0.30450325],
        [0.28018962, 0.69814875, 0.01363837],
        [0.9153463 , 0.62422975, 0.52875965],
        [0.65950125, 0.39873671, 0.44682769],
        [0.79994595, 0.05841742, 0.65758876],
        [0.51880505, 0.17120824, 0.86022041],
        [0.09429731, 0.26885909, 0.00562214],
        [0.33708341, 0.33494163, 0.86525517],
        [0.22313379, 0.56702977, 0.75343146],
        [0.76760012, 0.53375076, 0.84560995],
        [0.7922605 , 0.93819166, 0.14569105],
        [0.93642419, 0.51689683, 0.01706509],
        [0.6514826 , 0.26154607, 0.34695317],
        [0.91146727, 0.7243165 , 0.12601475],
        [0.02393432, 0.859428  , 0.96297084],
        [0.78970059, 0.52408596, 0.93308251]],

       [[0.56522788, 0.23632564, 0.71326253],
        [0.61576589, 0.22287723,

In [45]:
np.random.randint(2,3,4)

array([2, 2, 2, 2], dtype=int32)

In [50]:
np.arange(1,13).reshape(3,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
a=np.random.randint(10,20)

In [58]:
a

10

In [63]:
a

10

In [65]:
b=np.random.randint(10,20,(5,4))
b

array([[10, 16, 17, 17],
       [13, 18, 18, 13],
       [10, 12, 18, 15],
       [15, 11, 19, 12],
       [10, 12, 11, 18]], dtype=int32)

In [66]:
b[:]

array([[10, 16, 17, 17],
       [13, 18, 18, 13],
       [10, 12, 18, 15],
       [15, 11, 19, 12],
       [10, 12, 11, 18]], dtype=int32)

In [67]:
b[1:3]

array([[13, 18, 18, 13],
       [10, 12, 18, 15]], dtype=int32)

In [69]:
b[-3]

array([10, 12, 18, 15], dtype=int32)

In [70]:
b[3:4]

array([[15, 11, 19, 12]], dtype=int32)